### ISSUE TITLE
Package errors after installation

### ISSUE THREAD

**Issue by mikerockett** [giftcards/ModRewrite#2]
Using PHP 5.6.19, I get the following errors after installation into a Silex app:

> **Strict Standards:** Non-static method Giftcards\ModRewrite\RewriterBuilder::create() should not be called statically in **\public_html\index.php** on line **12**
> 
> **Catchable fatal error:** Argument 1 passed to Giftcards\ModRewrite\Compiler\Compiler::__construct() must be an instance of Giftcards\ModRewrite\Compiler\Lexer, null given, called in \vendor\giftcards\mod-rewrite\src\Giftcards\ModRewrite\Compiler\CompilerBuilder.php on line 31 and defined in **\vendor\giftcards\mod-rewrite\src\Giftcards\ModRewrite\Compiler\Compiler.php** on line **17**

Used the following code:

``` php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use Giftcards\ModRewrite\Compiler\CompilerBuilder;
use Giftcards\ModRewrite\RewriterBuilder;
use Symfony\Component\HttpFoundation\Request;

$app = new Silex\Application();

$app->get('/', function (Request $request) {
    $rewriter = RewriterBuilder::create()->build();
    $compiler = CompilerBuilder::create()->build();
    $file = __DIR__ . '/testfile.modrewrite';

    return $rewriter->rewrite(
        rawurldecode($request->getPathInfo()),
        $request,
        $compiler->compile(file_get_contents($file))
    );
});

$app->run();
```

Any ideas?

**Comment by yjv** [comment]
@mikerockett i put an update in to fix that. looks like the compiler builder didnt actually return a defasult lexer or parser when it wasnt set. 1.0.4 fixes that. Let me know if that does it.

Thanks!

**Comment by yjv** [comment]
Also didnt mark create on the RewriterBuilder as static

**Comment by mikerockett** [comment]
Hi, thanks for the quick response.

I'm not seeing any commits?

**Comment by yjv** [comment]
yeah i know :(. github looks likeits having an issue showing updates like that. though i checked git many times it should be pushed so hopefully as soon as they fix it, it will show up here and in packagist.

Thanks!

**Comment by mikerockett** [comment]
Weird indeed. Well I saw the commit from the tag push, so updated from there. Thanks - appears to be working now. :+1:

**Comment by yjv** [comment]
awesome!
