### ISSUE TITLE
Rule subject in htaccess context

### ISSUE THREAD

**Issue by mikerockett** [giftcards/ModRewrite#3]
In the htaccess context, developers should not use the leading slash in their rules (`^/...`). As I understand it, your package (which is awesome, by the way) is built for the server config/vhost context.

Could you perhaps consider adding support for the htaccess context?

**Comment by yjv** [comment]
yeah possibly. Ill see if i can find some time to look into it. all the links you can give on this and elaboration would be great. Also PRs are always welcome ;)

**Comment by mikerockett** [comment]
I'm afraid I'm not very familiar with parsers, lexers, and the like, but I'll have a look and see what I can come up with.

A bit of elaboration on the matter: `mod_rewrite` behaves differently in the `Directory` and `.htaccess` context vs. the `VirtualHost` context. General information about that can be found [here](http://tltech.com/info/rewriterule-in-htaccess-vs-httpd-conf/).

Philipp Tempel wrote a gist about [how context affects syntax](https://gist.github.com/philipptempel/4593639#context-affects-syntax) as well.

Hope that sheds a little light on the issue. :smile:

**Comment by yjv** [comment]
@mikerockett it looks like the difference is not in parsing lexing or matching but what is actually passed to the Rewriter's $pathInfo arg. The docs about the difference look like theyre saying that in an .htaccess context the url is passed as relative to the current location (which makes sense considering its read in a recursive dir fashion relative to whatevere dir its in). So it looks like this may be outside the area that this library is in charge of. If you pass the path info without the leading slash in an .htaccess context it should work like those docs say. 

If I'm missing something please I want to know but thats what it looks like.

Thanks! :)

**Comment by yjv** [comment]
Just saw the part about the L flag. The library doesnt actually support the

**Comment by yjv** [comment]
Just saw the part about the L flag. The library doesnt actually support the L flag yet :) since it always exits on first match. so i guess in that way its always worked like .htaccess :). I think that with a little bit of tweeking it can be made to work that way but i  havet been able to get time to sit down and do that.

**Comment by mikerockett** [comment]
I see your point indeed. I could picture a scenario where you pass certain variables to the library for this purpose - such as setting the context and directory. Regarding the L flag, that isn't a true 'exit', as the file continues to be parsed anyway - you can rewrite your rewrites. The END flag is the true 'exit' as it stops processing then and there, without any hesitation whatsoever.

Anyway, the reason I brought this up is because I'd like to put together a simple htaccess tester that is more effective than the one at http://htaccess.mwl.be, so these issues are pertinent to make it more efficient, and giving more accurate results to testers.
